[parser]
fence_sequence = "```"
fence_sequence_alt = "~~~"

comment_start = "#-"
comments_as_aside = false

macro_start = "# ==>"
macro_end = "."

transclusion_start = "@{{"
transclusion_end = "}}"

link_prefix = "@"

file_prefix = "file:"
hidden_prefix = "hidden:"

interpolation_start = "@{"
interpolation_end = "}"
variable_sep = ":"

[paths]
root = "."
code = "code/"
docs = "docs/"

files = ["README.md"]
entrypoint = "Main" # Avoids adding unnamed blocks to code output

[language.py]
clear_blank_lines = false
eof_newline = true

    # [language.py.block_labels]
    # comment_start = "#"
    # block_start = "<@"
    # block_next = "<@>"
    # block_end = "@>"
    # name_separator = "#"
