language: rust
env:
  global:
    - REPO=yarner

os:
  - linux
  - windows
  - osx

rust:
  - stable

branches:
  only:
    - master
    - dev
    - "/^\\d+\\.\\d+\\.\\d+/"

script:
  - rustup component add rustfmt clippy
  - cargo fmt -- --check
  - cargo clippy --all-targets -- --deny warnings
  - cargo test --verbose
  - cargo build --release

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

before_deploy:
  - rm -rf ${REPO} || exit 0
  - mkdir ${REPO}
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -f target/release/yarner ${REPO} > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp -f target/release/yarner ${REPO} > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cp -f target/release/yarner.exe ${REPO} > /dev/null; fi
  - tar -czf ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz ${REPO}

deploy:
  provider: releases
  skip_cleanup: true
  token:
    secure: HtBT8zRgT1SaDlM9x6uIjzxXDg3GmslmlSOylHqDWBAMaeCzjPklgfRcdFlCPkyHCTs/UsKWBcbSx25zI1prWDGr8vbnWBtKh9C+C1iZLV3Ezbul7Q47JX8Ne0jLy4UNrpSn1rfaihM77LW7sE8buUK9L/WpMqsRTvvvxEkDZWMJ4zazB0RV/zVTdStZJuWUN8bKeLReV0CwIYhf5+5GLeA+kIY8oTCSUo+sP15Rsb7vg25/2/vvgkwPbwtMJwPbim73uqtY5/PvXvUlMv3MX6/u2PuYFljnEEDIHK7VSjazrveY2qfZ5qIx8nbWGYDgVHTurFph5dPtIhzYguLZaRCd1H3f3ILOmbzpkC5Jn0ASk+UptEvCMkm0Uk69RBVnGXBsRKWnctcNmrXM846R68T7p/MEZArskEwLLs86NZNkveDKe2M+cjf6Gp7kZhOdKcyC34i3AI6It6bbabYWrwrqnfp1xdja6gqnnvNomOv/zqKTZUdMWp+I184w+IQmWfzzY9/cQX72WpAor98Ke3MKoY3Rnb0YN+DtgxboWtzrBAHHDGpf1+a+Qyq/Nt9aciV47adld2i4wAncKLEWaiO2dnYqmJbx82k+qijYCZ/tJ3tHwwIPchECXK7WHG5sitqw9iC7EV5Sqx4xL2ODLY304PCcRtPVpf14k++NzDM=
  file: ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz
  on:
    tags: true
    all_branches: true
