language: rust
env:
  global:
    - REPO=yarner

os:
  - linux
  - windows
  - osx

rust:
  - stable

branches:
  only:
    - master
    - dev
    - "/^\\d+\\.\\d+\\.\\d+/"

script:
  - rustup component add rustfmt clippy
  - cargo fmt -- --check
  - cargo clippy --all-targets -- --deny warnings
  - cargo test --verbose
  - cargo build --release --features="bin"

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

before_deploy:
  - rm -rf ${REPO} || exit 0
  - mkdir ${REPO}
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -f target/release/yarner ${REPO} > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp -f target/release/yarner ${REPO} > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cp -f target/release/yarner.exe ${REPO} > /dev/null; fi
  - tar -czf ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz ${REPO}

deploy:
  provider: releases
  skip_cleanup: true
  token:
    secure: KsAgWs7M1S4x2tO60kqjgqHjU72UFN4GMluHr2KHCRuwVZOGSrlh0GqB8MsB4W3XzSCdgc1lFQB6SvIKaA4sEaKCgVtd8w0mVK06WlpEq8EmRBdHxOEeT+9f0PPNBLjQ/dpj1lJtE7gEJiKdgdAL0SzmdecOPnWtqPgk6k7k6Qv4gfkUOVe721hRGl7rTEjLXmIhRqaX5Azcm1zXCyWFGZoUKpLcce0rA62meup3Xv78GCywHVx83GDUw8WaukMw3eSbcKLahQV3qc3RU5OLT8ZpD+NZpdxM59PBydpNAwu8fdSqEEUzu8L3eePm0T0K0RwEWZQDmrUYPHIwyYTVstAT88Ch6ACwrM7TwV2PbqTeMbDULfVIe8XBjYJPa2EWzRw8k4Wdpas+6YZwXtoempCKq74psJrgekPnbyTyS9NOo5KlM5HALE77Rs0Fn3MSFglVMxLCn9vtAxFRs3zxRhwHOWF+Z6BTeDPQs3nmhxWVJKHLLQnGzZsSEa5ZL5+CNa4OnIMLRq9nc4yR8/MIactPBCuN8bp0MYixi7wgSs/mTAy3wVDcR8PyQOGeYIZdezsp5mAw9aleBFizgCszb5Qgc+KWPQsnFtY6tO18po9OPiT6ZpzqlkFIBQckcTT1ra37CJbl5zu7qgiP50IuW7f1KeXUvrXXDW/FIjUaFUM=
  file: ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz
  on:
    tags: true
    all_branches: true
