[tex]

# The environment used to indicate code.
code_environment = "code"

# The sequence to identify a comment which should be omitted from the compiled code.
comment_start = "//"

# The sequence to identify the start of a meta variable interpolation.
interpolation_start = "@{"
# The sequence to identify the end of a meta variable interpolation.
interpolation_end = "}"

# The sequence to identify the start of a macro invocation.
macro_start = "==> "
# The sequence to identify the end of a macro invocation.
macro_end = "."

# The sequence to split variables into name and value.
variable_sep = ":"

# Prefix for file-specific entry points.
file_prefix = "file:"

# Name prefix for code blocks not shown in the docs.
hidden_prefix = "hidden:"

[paths]
# Code output path.
code = "code/"
# Docs output path.
docs = "docs/"
# Input file(s).
files = ["%%MAIN_FILE%%"]
