[html]
# The tag that code is written in when parsing.
# When printing, the code is always rendered in`<pre><code></code></pre>`, as is recommended by W3C.
code_tag = "code"

# The attribute to put the language name when rendering the documentation.
language_attribute = "data-language"

# The attribute to add to the `code_tag` with the code block's name .
name_attribute = "data-name"

# A class to add to the `<pre>` container for any parsed blocks of code when rendering.
block_class = "block"

# The class to add to the `<code>` block when rendering.
# The string `{}` is replaced with the language that this block is in.
language_class = "language-{}"

# Parsed comments are stripped from the code and written to an `<aside></aside>` block after the code when printing.
# If false, the comments are just written back into the code.
comments_as_aside = false

# The sequence to identify a comment which should be omitted from the compiled code.
comment_start = "//"

# The sequence to identify the start of a meta variable interpolation.
interpolation_start = "@{"
# The sequence to identify the end of a meta variable interpolation.
interpolation_end = "}"

# The sequence to identify the start of a macro invocation.
macro_start = "==> "
# The sequence to identify the end of a macro invocation.
macro_end = "."

# The sequence to split variables into name and value.
variable_sep = ":"

# Prefix for file-specific entry points.
file_prefix = "file:"

# Name prefix for code blocks not shown in the docs.
hidden_prefix = "hidden:"

# The language to set if there was no automatically detected language. Optional.
## default_language = "c"

[paths]
# Code output path.
code = "code/"
# Docs output path.
docs = "docs/"
# The input source file(s) as glob pattern(s).
files = ["%%MAIN_FILE%%"]
# File(s) to include in code output (unprocessed), as glob pattern(s).
## code_files = ["**/*.rs"]
# File(s) to include in docs output (unprocessed), as glob pattern(s).
## doc_files = ["**/*.png", "**/*.jpg"]
# Entrypoint block name. Optional. If not supplied, unnamed code blocks are used.
## entrypoint = "Main"
