[parser]
fence_sequence = "```"
fence_sequence_alt = "~~~"

comment_start = ";-"
comments_as_aside = false

macro_start = "; ==>"
macro_end = "."

transclusion_start = "@{{"
transclusion_end = "}}"

link_prefix = "@"

file_prefix = "file:"
hidden_prefix = "hidden:"

[paths]
root = "."
code = "code/"
docs = "docs/"
files = ["README.md"]
entrypoint = "Main" # Avoids writing unnamed code blocks

[language.nls]
clear_blank_lines = true
eof_newline = true

    [language.nls.block_labels]
    comment_start = ";"
    block_start = "<@"
    block_next = "<@>"
    block_end = "@>"
