[bird]
code_marker = "> "
code_name_marker = ">>> "
comment_start = "//"
interpolation_start = "@{"
interpolation_end = "}"
macro_start = "==> "
macro_end = "."
variable_sep = ":"
file_prefix = "file:"
hidden_prefix = "hidden:"

[paths]
code = "__code/"
docs = "__docs/"
files = ["wc.c.bird"]
