[md]
fence_sequence = "```"
fence_sequence_alt = "~~~"
block_name_start = " - "
comments_as_aside = false
comment_start = "//"
interpolation_start = "@{"
interpolation_end = "}"
macro_start = "==> "
macro_end = "..."
transclusion_start = "@{{"
transclusion_end = "}}"
variable_sep = ":"
file_prefix = "file:"
hidden_prefix = "hidden:"
blank_lines = true

[paths]
code = "__code/"
docs = "__docs/"
files = ["Rabies.nlogo.md"]
