[parser]
fence_sequence = "```"
fence_sequence_alt = "~~~"

block_name_prefix = "//-"

macro_start = "// ==>"
macro_end = "."

transclusion_start = "@{{"
transclusion_end = "}}"

link_prefix = "@"

file_prefix = "file:"
hidden_prefix = "hidden:"

[paths]
root = "."
code = "code/"
docs = "docs/"

files = ["README.md"]
entrypoint = "Main" # Avoids adding unnamed blocks to code output

[language.rs]
clear_blank_lines = true
eof_newline = true

    [language.rs.block_labels]
    comment_start = "//"
    block_start = "<@"
    block_next = "<@>"
    block_end = "@>"
