name: Crates.io

on:
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publish library
        uses: katyo/publish-crates@v1
        with:
          path: './yarner-lib'
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
      - name: Wait 15 seconds
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '15s'
      - name: Publish binaries
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
